name: ScafiWeb frontend deploy

on:
    push:
        tags:        
          - '*' 
jobs:
  Build:
    strategy:
      # Using matrix build even if not needed
      matrix:
        os: [ ubuntu-latest ]
        jvm_version: [ 11 ]
    runs-on: ${{ matrix.os }}
    env:
      JAVA_VERSION: ${{ matrix.jvm_version }}
      OS: ${{ matrix.os }}
      TERM: dumb
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Setup Scala with Java ${{ matrix.jvm_version }}
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.${{ matrix.java }}
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Sbt test
        run: sbt test
      - name: Build project scafi-web project with SBT
        run:  sbt -v "project frontend; fullOptJS::webpack"
      - name: Build compiler
        run: sbt "project online-compiler; assembly"

      - name: Adjust folders for deployment
        shell: bash
        run: .github/scripts/adjust-deployment.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: scafi/web 
          publish_dir: ./public
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Upload compiler service to Docker Hub
        shell: bash
        run: .github/scripts/docker-release.sh

