name: ScafiWeb frontend deploy

on: [push, workflow_dispatch]
jobs:
  Build:
    strategy:
      # Using matrix build even if not needed
      matrix:
        os: [ ubuntu-latest ]
        jvm_version: [ 11 ]
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup Scala with Java ${{ matrix.jvm_version }}
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.${{ matrix.java }}
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Sbt test
        run: sbt test
